[package]
name = "ebur128"
version = "0.1.1"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"
categories = ["multimedia"]
keywords = ["multimedia", "audio", "dsp"]
description = "Implementation of the EBU R128 loudness standard"
repository = "https://github.com/sdroege/ebur128"
homepage = "https://github.com/sdroege/ebur128"
license = "MIT"
readme = "README.md"

[dependencies]
bitflags = "1.0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.3"
float-cmp = "0.8"
ebur128-c = { package = "ebur128", version = "=0.1.1" }

[features]
internal-tests = []

[[bench]]
name = "interp"
harness = false

[[bench]]
name = "true_peak"
harness = false

[[bench]]
name = "ebur128"
harness = false
